### ISSUE TITLE
When shrinking height O3 goes up into the top bar

### ISSUE THREAD

**Issue by saltyskip** [O3Labs/o3.network#10]
![image](https://user-images.githubusercontent.com/14796429/52266451-cab2ae00-2979-11e9-8cc7-9629aaba431e.png)

To Reproduce shrink browser window height

**Comment by creyeknife** [comment]
What browser is this in?

**Comment by creyeknife** [comment]
Oh never mind, can reproduce.

**Comment by creyeknife** [comment]
I have fixed it for most cases, it will still happen if the someone displays the website in mobile view on desktop and edits the browser height but that seems like an edge case I think. It works fine on mobile view because you cannot edit the browser height.
